name: linter

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb', 'bun.lock', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun install --frozen-lockfile

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: bun run format

      - name: Lint Frontend
        run: bun run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix code style
          commit_options: '--no-verify'
